runtime: nodejs20

instance_class: F2

runtime_config:
  operating_system: ubuntu22

service: discord

inbound_services:
- warmup

handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /_ah/warmup
  script: dist/warm.js

automatic_scaling:
  min_instances: 1